spring.application.name=api

# CONEXION BASE DE DATOS
spring.datasource.url=jdbc:postgresql://localhost:5432/EasyRMP_db
spring.datasource.username=postgres
spring.datasource.password=rai290905

# CONFIGURACION HIBERNATE
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect